### ISSUE TITLE
payload errors

### ISSUE THREAD

**Issue by FedericoOldrini** [Cameo-dev/node-red-contrib-google-docs#3]
Hi, I have some problem setting up a replace request for google slide. The ui seems to be broken and I have errors in debug view. Tried on chrome and safari.

<img width="843" alt="Schermata 2020-09-16 alle 23 13 26" src="https://user-images.githubusercontent.com/3073877/93393241-70c2db80-f872-11ea-8e40-cf7a91627ec2.png">

**Comment by FedericoOldrini** [comment]
The UI now is working, i will have a try later of the flow. Thanks!

**Comment by JbIPS** [comment]
Nvm, I found it and v0.0.4 fix it!

Feel free to re-open if the issue persists.
